### PR TITLE
retry logic, close #818

### LINKED ISSUE #818: provide configuration to auto shutdown client with problems
* example case: DNS is misconfigured and it floods the memory and logs retrying to get the credentials

Example Exception: `java.net.UnknownHostException: auth.sphere.io: unknown error`

### PR DESCRIPTION
**Pull request by schleichardt**

### CODE REVIEW

File: commercetools-java-client-core/src/main/java/io/sphere/sdk/client/AuthActor.java [hunk 1]
```diff
@@ -1,93 +1,90 @@
...
-        final Long delayInSecondsToFetchNewToken = Optional.ofNullable(tokens.getExpiresIn()).map(ttlInSeconds -> ttlInSeconds - 60 * 60).orElse(60 * 30L);
+        final Long delayInSecondsToFetchNewToken = Optional.ofNullable(tokens.getExpiresIn())
+                .map(ttlInSeconds -> selectNextRetryTime(ttlInSeconds))
+                .orElse(60L);
         schedule(new FetchTokenFromSphereMessage(), delayInSecondsToFetchNewToken, TimeUnit.SECONDS);
     }
 
+    static Long selectNextRetryTime(final Long ttlInSeconds) {
+        final long aDay = 60 * 60 * 24L;
+        final long min = Math.min(ttlInSeconds / 2, aDay);
```
Comment (lauraluiz) [inline commercetools-java-client-core/src/main/java/io/sphere/sdk/client/AuthActor.java]: Better call it `minimum` to avoid confusion with minutes

File: commercetools-sdk-base/src/main/java/io/sphere/sdk/retry/AsyncRetrySupervisorImpl.java [hunk 2]
```diff
@@ -0,0 +1,121 @@
...
+                final Object parameter = retryStrategy.getParameter();
+                retryContext.schedule(() -> {
+                    final CompletionStage<R> completionStage = forceApply(function, parameter);
+                    handleResultAndEnqueueErrorHandlingAgain(completionStage, parameter, retryContext);
+                }, duration);
+            } else {
+                throw new IllegalStateException("illegal state for " + retryStrategy);
+            }
+        }
+    }
```
Comment (lauraluiz) [inline commercetools-sdk-base/src/main/java/io/sphere/sdk/retry/AsyncRetrySupervisorImpl.java]: You might refactor this

File: commercetools-sdk-base/src/main/java/io/sphere/sdk/retry/RetryAction.java [hunk 3]
```diff
@@ -0,0 +1,153 @@
...
+import java.util.function.Function;
+
+import static io.sphere.sdk.retry.RetryActions.validateMaxAttempts;
+
+/**
+ * Selects for a {@link RetryContext} which error handling strategy ({@link RetryStrategy}) should be used like
+ * resume (keep internal state and throw latest exception),
+ * retry immediately,
+ * retry scheduled
+ * or stop the service (don't do it if you really have a good reason).
```
Comment (lauraluiz) [inline commercetools-sdk-base/src/main/java/io/sphere/sdk/retry/RetryAction.java]: Don't do it unless you have a really good reason

File: commercetools-sdk-base/src/main/java/io/sphere/sdk/retry/RetryAction.java [hunk 4]
```diff
@@ -0,0 +1,153 @@
...
+                } else {
+                    final Duration duration = durationFunction.apply(retryOperationContext);
+                    final Object parameterObject = retryOperationContext.getLatestParameter();
+                    return RetryStrategy.retryScheduled(parameterObject, duration);
+                }
+            }
+
+            @Override
+            protected String getDescription() {
+                return "schedule retry retry up to " + maxAttempts + " times";
```
Comment (lauraluiz) [inline commercetools-sdk-base/src/main/java/io/sphere/sdk/retry/RetryAction.java]: - retry

File: commercetools-convenience/src/test/java/io/sphere/sdk/client/retry/RetrySphereClientDecoratorTest.java [hunk 5]
```diff
@@ -0,0 +1,95 @@
...
+                            "  \"errors\" : [ {\n" +
+                            "    \"code\" : \"ConcurrentModification\",\n" +
+                            "    \"message\" : \"Version mismatch. Concurrent modification.\",\n" +
+                            "    \"currentVersion\" : 7\n" +
+                            "  } ]\n" +
+                            "}"));
+                } else if (httpRequest.getUrl().contains("version=7")) {
+                    return CompletableFuture.completedFuture(HttpResponse.of(200, "{\"id\": \"some-id\", \"version\": 7}"));
+                } else {
+                    throw new IllegalArgumentException("unexcpected input");
```
Comment (lauraluiz) [inline commercetools-convenience/src/test/java/io/sphere/sdk/client/retry/RetrySphereClientDecoratorTest.java]: unexpected

File: commercetools-sdk-base/src/main/java/io/sphere/sdk/retry/AsyncRetrySupervisorImpl.java [hunk 6]
```diff
@@ -0,0 +1,121 @@
...
+            if (isErrorCase) {
+                final RetryContextImpl<P, R> nextContext = retryOperationContext.withNewFailedAttempt(error, parameter);
+                handle(nextContext);
+            } else {
+                retryOperationContext.getResult().complete(res);
+            }
+        }, executor);
+    }
+
+    private RetryAction getRetryOperation(final RetryContext retryContext) {
```
Comment (lauraluiz) [inline commercetools-sdk-base/src/main/java/io/sphere/sdk/retry/AsyncRetrySupervisorImpl.java]: getRetryAction

File: commercetools-sdk-base/src/main/java/io/sphere/sdk/retry/RetryRule.java [hunk 7]
```diff
@@ -0,0 +1,44 @@
...
+    boolean test(RetryContext retryContext);
+
+    /**
+     * Applies the retry rule.
+     * Should not be called if {@link #test(RetryContext)} would yield false for {@code retryContext}.
+     *
+     * @param retryContext
+     * @return
+     */
+    RetryAction apply(RetryContext retryContext);
```
Comment (schleichardt) [inline commercetools-sdk-base/src/main/java/io/sphere/sdk/retry/RetryRule.java]: return RetryStrategy

**Comment by schleichardt** [comment]
@lauraluiz I added two commits which you should review.

File: commercetools-sdk-base/src/main/java/io/sphere/sdk/retry/AsyncRetrySupervisorImpl.java [hunk 8]
```diff
@@ -59,36 +60,40 @@ private void schedule(final Runnable r, final Duration d) {
...
+            final Object parameter = retryStrategy.getParameter();
+            if (strategyType == StrategyType.RETRY_IMMEDIATELY) {
+                retry(retryContext, function, parameter);
+            } else if (strategyType == StrategyType.RETRY_SCHEDULED) {
                 final Duration duration = retryStrategy.getDuration();
-                final Object parameter = retryStrategy.getParameter();
-                retryContext.schedule(() -> {
-                    final CompletionStage<R> completionStage = forceApply(function, parameter);
-                    handleResultAndEnqueueErrorHandlingAgain(completionStage, parameter, retryContext);
-                }, duration);
```
Comment (lauraluiz) [inline commercetools-sdk-base/src/main/java/io/sphere/sdk/retry/AsyncRetrySupervisorImpl.java]: 👍

**Comment by lauraluiz** [comment]
👍
