### PR TITLE
Fixing NPE when using draft builder with empty fields,

### LINKED ISSUE #1514: plusFieldDefinitions causes NPE
I wrote a test to show the exception:

```java
import io.sphere.sdk.categories.Category;
import io.sphere.sdk.models.LocalizedString;
import io.sphere.sdk.types.FieldDefinition;
import io.sphere.sdk.types.ReferenceFieldType;
import io.sphere.sdk.types.ResourceTypeIdsSetBuilder;
import io.sphere.sdk.types.TypeDraftBuilder;
import org.junit.Test;

import java.util.Locale;

public class DemoTest {

    @Test
    public void plusFieldDefinitions() throws Exception {
        final LocalizedString l = LocalizedString.of(Locale.GERMAN, "l");
        final TypeDraftBuilder builder = TypeDraftBuilder.of("type-key", l, ResourceTypeIdsSetBuilder.of().addCategories());
        builder.plusFieldDefinitions(FieldDefinition.of(ReferenceFieldType.of(Category.referenceTypeId()), "fieldName", l, false)).build();
        /*
        java.lang.NullPointerException
        at io.sphere.sdk.utils.SphereInternalUtils.listOf(SphereInternalUtils.java:51)
        at io.sphere.sdk.types.TypeDraftBuilder.plusFieldDefinitions(TypeDraftBuilder.java:22)
        at io.sphere.sdk.types.TypeDraftBuilder.plusFieldDefinitions(TypeDraftBuilder.java:27)
        at DemoTest.plusFieldDefinitions(DemoTest.java:17)
         */
    }
}
```

### PR DESCRIPTION
**Pull request by acbeni**
Closes #1514

### CODE REVIEW

File: commercetools-models/src/main/java/io/sphere/sdk/types/TypeDraftBuilder.java [hunk 1]
```diff
@@ -19,8 +17,10 @@ public static TypeDraftBuilder of(final String key, final LocalizedString name,
     }
 
     public TypeDraftBuilder plusFieldDefinitions(final List<FieldDefinition> fieldDefinitions) {
-        this.fieldDefinitions = SphereInternalUtils.listOf(getFieldDefinitions(), fieldDefinitions);
+
+        this.fieldDefinitions = SphereInternalUtils.listOf(Optional.ofNullable(getFieldDefinitions()).orElseGet(ArrayList::new), fieldDefinitions);
```
Comment (katmatt) [inline commercetools-models/src/main/java/io/sphere/sdk/types/TypeDraftBuilder.java]: Nice 👍

File: commercetools-models/src/test/java/io/sphere/sdk/types/TypeDraftBuilderTest.java [hunk 2]
```diff
@@ -0,0 +1,20 @@
+package io.sphere.sdk.types;
+
+import io.sphere.sdk.categories.Category;
+import io.sphere.sdk.models.LocalizedString;
+import org.junit.Test;
+
+import java.util.Locale;
+
+public class TypeDraftBuilderTest {
```
Comment (katmatt) [inline commercetools-models/src/test/java/io/sphere/sdk/types/TypeDraftBuilderTest.java]: Great that you added an unit test here 👍
