### PR TITLE
#1940 paged search result serialization

### LINKED ISSUE #1940: PagedSearchResult#empty() can't be serialized
Trying to serialized PagedSearchResult#empty() will throw jackson exception because because the "limit" field is set to 0, and PagedSearchResult#getPageIndex() throws exception if limit is 0.

### PR DESCRIPTION
**Pull request by alex-ct**
# Description

Closes #1940 

# Checklist

- [x] Update release Notes
- [ ] Add to the current github milestone 
- [ ] Update commercetools api reference

### CODE REVIEW

File: commercetools-sdk-base/src/test/java/io/sphere/sdk/search/PagedSearchResultTest.java [hunk 1]
```diff
@@ -85,7 +86,15 @@ public void rangeFacetOfAllRangesWithOnlyNegativeRange() throws Exception {
                         RangeStats.of("0.0", null, 0L, null, "0.0", "0.0", "0.0", 0.0)),
                 simpleRangeStats -> assertThat(simpleRangeStats).isEqualTo(SimpleRangeStats.of(null, null, 6L, "-10.0", "-3.0")));
     }
-
+    
+    @Test
```
Comment (acbeni) [inline commercetools-sdk-base/src/test/java/io/sphere/sdk/search/PagedSearchResultTest.java]: cool 💯 , guess this PR is ready to go ✈️
