### PR TITLE
Sphere project scope to string, close #1455

### LINKED ISSUE #1455: SphereProjectScope is incomplete
io.sphere.sdk.client.SphereProjectScope is missing at least CREATE_ANONYMOUS_TOKEN

https://dev.commercetools.com/http-api-authorization.html#scopes

```
Exception in thread "main" java.lang.IllegalArgumentException: No enum constant io.sphere.sdk.client.SphereProjectScope.CREATE_ANONYMOUS_TOKEN
	at java.lang.Enum.valueOf(Enum.java:238)
	at io.sphere.sdk.client.SphereProjectScope.valueOf(SphereProjectScope.java:3)
	at io.sphere.sdk.client.SphereProjectScope.ofScopeString(SphereProjectScope.java:50)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at io.sphere.sdk.client.SphereClientConfigUtils.scopesAsCommaSeparatedStringsToList(SphereClientConfigUtils.java:90)
	at io.sphere.sdk.client.SphereClientConfigUtils.ofProperties(SphereClientConfigUtils.java:77)
	at io.sphere.sdk.client.SphereClientConfig.ofProperties(SphereClientConfig.java:160)
```

### PR DESCRIPTION
**Pull request by ccsalazarr-commercetools**
@katmatt could you review it, please... But I have a question, is it worthwhile to add the missing scopes into the class?, or is it enough to have the `of(String scope)` factory method?

### CODE REVIEW

File: commercetools-sdk-base/src/main/java/io/sphere/sdk/client/SphereProjectScope.java [hunk 1]
```diff
@@ -1,52 +1,94 @@
...
+    public final static SphereProjectScope VIEW_PROJECT_SETTINGS = SphereProjectScope.of("view_project_settings");
+
+    /** Grants access to the APIs for creating, modifying and viewing anything related to states in a project.*/
+    public final static SphereProjectScope MANAGE_STATES = SphereProjectScope.of("manage_states");
+
+    /** Grants access to the APIs for viewing anything related to states in a project.*/
+    public final static SphereProjectScope VIEW_STATES = SphereProjectScope.of("view_states");
+
+    /** Grants access to the APIs for viewing anything related to messages in a project.*/
+    public final static SphereProjectScope VIEW_MESSAGES = SphereProjectScope.of("view_messages");
```
Comment (katmatt) [inline commercetools-sdk-base/src/main/java/io/sphere/sdk/client/SphereProjectScope.java]: I really like that you added the missing scopes 👍

File: commercetools-sdk-base/src/test/java/io/sphere/sdk/client/SphereProjectScopeTest.java [hunk 2]
```diff
@@ -1,18 +1,47 @@
...
-import static org.assertj.core.api.Assertions.*;
+import static io.sphere.sdk.client.SphereProjectScope.*;
+import static org.assertj.core.api.Assertions.assertThat;
 
 public class SphereProjectScopeTest {
+
     @Test
     public void toSphereScope() {
         assertThat(MANAGE_PROJECT.toScopeString()).isEqualTo("manage_project");
+        assertThat(MANAGE_PRODUCTS.toScopeString()).isEqualTo("manage_products");
```
Comment (katmatt) [inline commercetools-sdk-base/src/test/java/io/sphere/sdk/client/SphereProjectScopeTest.java]: Nice that you added more test cases 👍 :1st_place_medal:

**Comment by katmatt** [comment]
@ccsalazarr-commercetools It's nice that you added the missing scopes, but since we are now using a class instead of an enum our SDK won't fail if it doesn't know about a scope.

**Comment by katmatt** [comment]
Closes #1455
