### PR TITLE
#1902 add line item structure fix

### LINKED ISSUE #1902: AddLineItem staged update action sends invalid payload to Sphere client
The `io.sphere.sdk.orderedits.commands.stagedactions.AddLineItem` staged update action causes a wrong payload to be sent to the Sphere client.
Consider the following (simplified) code:
```
Reference<Order> orderReference = Order.referenceOfId("3cf5625e-048a-455d-9d1d-b92bcc842f81");
LineItemDraft lineItemDraft = LineItemDraft.of("3577350d-0065-4b8d-a162-07bf3b8a2d49", 1, 3);
List<StagedUpdateAction<OrderEdit>> stagedActions = Collections.singletonList(AddLineItem.of(lineItemDraft));
OrderEditDraft orderEditDraft = OrderEditDraftBuilder.of(orderReference, stagedActions).build();
blockingSphereClient.executeBlocking(OrderEditCreateCommand.of(orderEditDraft));
```
This sends the following payload to the client:
```
{
    "resource": {
        "typeId": "order",
        "id": "3cf5625e-048a-455d-9d1d-b92bcc842f81"
    },
    "stagedActions": [{
        "action": "addLineItem",
        "lineItem": {
            "productId": "3577350d-0065-4b8d-a162-07bf3b8a2d49",
            "quantity": 3,
            "variantId": 1
        }
    }]
}
```
This returns the following error message from the Sphere client:  `"LineItem error: The product must be identified either by 'productId' or 'sku'."`
The following payload is correct however:
```
{
    "resource": {
        "typeId": "order",
        "id": "3cf5625e-048a-455d-9d1d-b92bcc842f81"
    },
    "stagedActions": [{
        "action": "addLineItem",
        "productId": "3577350d-0065-4b8d-a162-07bf3b8a2d49",
        "quantity": 3,
        "variantId": 1
    }]
}
```
So it looks like `io.sphere.sdk.orderedits.commands.stagedactions.AddLineItem` needs to be modified so the correct payload is generated.

P.S. the same issue happens when an `sku` is used to identify the product.

### PR DESCRIPTION
**Pull request by alex-ct**
…t AddLineItem update action.

# Description

Closes #1902 

# Checklist

- [x] Update release Notes
- [x] Add to the current github milestone 
- [ ] Update commercetools api reference

### CODE REVIEW

File: commercetools-models/src/test/java/io/sphere/sdk/orderedit/commands/stagedactions/OrderEditStagedActionsIntegrationTest.java [hunk 1]
```diff
@@ -244,7 +244,7 @@ public void setLineItemShippingDetails() {
 
     @Test
     public void addLineItem() {
-        withProduct(client(), product -> {
+        ProductFixtures.withTaxedProduct(client(), product -> {
```
Comment (katmatt) [inline commercetools-models/src/test/java/io/sphere/sdk/orderedit/commands/stagedactions/OrderEditStagedActionsIntegrationTest.java]: Here it would be nice to use a static import, just for consistency 😉
